// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYTGj6WOgwmTyoyL4q0b6arcjx8NX915M',
    appId: '1:458343154528:web:dfb10e9faff2fcc61fd405',
    messagingSenderId: '458343154528',
    projectId: 'chatly-4ce85',
    authDomain: 'chatly-4ce85.firebaseapp.com',
    storageBucket: 'chatly-4ce85.firebasestorage.app',
    measurementId: 'G-NP2E9347TX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5kN_h7OM5m0irQ7ORgbS-v7DVdtXEwNY',
    appId: '1:458343154528:android:3531e89e5fe676031fd405',
    messagingSenderId: '458343154528',
    projectId: 'chatly-4ce85',
    storageBucket: 'chatly-4ce85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIL-G7-eVrJmx5YL3wKqiiDezyKgJzgUc',
    appId: '1:458343154528:ios:5c996803d39801b41fd405',
    messagingSenderId: '458343154528',
    projectId: 'chatly-4ce85',
    storageBucket: 'chatly-4ce85.firebasestorage.app',
    iosBundleId: 'com.example.chatly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIL-G7-eVrJmx5YL3wKqiiDezyKgJzgUc',
    appId: '1:458343154528:ios:5c996803d39801b41fd405',
    messagingSenderId: '458343154528',
    projectId: 'chatly-4ce85',
    storageBucket: 'chatly-4ce85.firebasestorage.app',
    iosBundleId: 'com.example.chatly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYTGj6WOgwmTyoyL4q0b6arcjx8NX915M',
    appId: '1:458343154528:web:f3611b5e92bbe9de1fd405',
    messagingSenderId: '458343154528',
    projectId: 'chatly-4ce85',
    authDomain: 'chatly-4ce85.firebaseapp.com',
    storageBucket: 'chatly-4ce85.firebasestorage.app',
    measurementId: 'G-YE0BRFFDYT',
  );
}
